name: 'Commit and push if the version file has changed'

inputs:
  name:
    description: 'The name of the commiter'
    required: true
    default: bot
  email:
    description: 'The email of the commiter'
    required: true
    default: 'bot@users.noreply.github.com'
  message:
    description: 'The commit message'
    required: true
    default: 'New release version(s)'
  files:
    description: 'The file(s) to add in the commit'
    required: true
    default: '*'
  directory:
    description: 'The directory (like submodule) in which the action will be performed'
    required: true
    default: '.'
  branch:
    description: 'Checkout (or create) on a specific branch before commit/push'
    required: true
    default: 'master'

runs:
  using: 'composite'
  steps:
    - run: |
        ORIGIN="$(pwd)"
        cd ${{ inputs.directory }}
        git switch ${{ inputs.branch }} 2>/dev/null || git switch -c ${{ inputs.branch }}
        CHANGES="$(git status --porcelain ${{ inputs.files }})"
        if [ -z "${CHANGES}" ]; \
        then \
          echo "No changes, stopping now"; \
          cd ${origin} \
          exit 0; \
        fi
        echo -e "Changes:\n${CHANGES}"
        git status # show off
        git config --global user.name ${{ inputs.name }}
        git config --global user.email ${{ inputs.email }}
        git add -f ${{ inputs.files }}
        git commit -am "${{ inputs.message }}"
        echo -----------------
        git status
        git log
        git branch
        echo ------------------
        # git push
      shell: bash
