name: Updating the SDK

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  updating_SDK:
    name: Updating the SDK
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build new SDK
        run: python tools/build_sdk.py

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Extract commit hash
        shell: bash
        run: echo "##[set-output name=commit;]$(echo ${git rev-parse --short \"$GITHUB_SHA\"})"
        id: extract_commit

      - name: Commit & push changes in the SDK if any
        uses: ./.github/actions/commit-changes
        with:
          directory: ethereum-plugin-sdk
          branch: ${{ steps.extract_branch.outputs.branch }}
          message: "[update] Branch ${{ steps.extract_branch.outputs.branch }} | Commit ${{ steps.extract_commit.outputs.commit }}"
